image: python:3.8.12-slim-bullseye

stages:
  - Test
  - Build

variables:
  PIPENV_VERBOSITY: -1
  PIPENV_CACHE_DIR: .cache/pipenv
  PIP_CACHE_DIR: .cache/pip

cache:
  paths:
    - .cache/pip
    - .cache/pipenv

before_script:
  - PATH=$PATH:~/.local/bin
  - apt update
  - apt install -y --no-install-recommends pkg-config libglib2.0-dev libcairo2-dev libgirepository1.0-dev python3-all-dev
  - python -m pip install --user pipx
  - python -m pipx ensurepath
  - pipx install pipenv
  - pipenv install --dev --skip-lock
  - . $(pipenv --venv)/bin/activate

pytest:
  stage: Test
  allow_failure: false
  script:
    - pytest

pytest-coverage:
  stage: Test
  script:
    - make pytest-coverage
  artifacts:
    reports:
      cobertura: coverage.xml

flake8-vula:
  stage: Test
  allow_failure: true # TODO set to false once code is clean enough
  script:
    - flake8 vula/

flake8-test:
  stage: Test
  allow_failure: true # TODO set to false once code is clean enough
  script:
    - flake8 test/

build:
  stage: Build
  allow_failure: false
  script:
    - apt install -y --no-install-recommends build-essential debhelper dh-python fakeroot git make python3-setuptools
    - make deb
    - dpkg -I deb_dist/*.deb
  artifacts:
    name: deb
    paths:
      - deb_dist/*.deb
