image: python:3.8.12-slim-bullseye

stages:
  - Test

variables:
  PIPENV_VERBOSITY: -1
  PIPENV_CACHE_DIR: .cache/pipenv
  PIP_CACHE_DIR: .cache/pip

cache:
  paths:
    - .cache/pip
    - .cache/pipenv

before_script:
  - PATH=$PATH:~/.local/bin
  - apt update
  - apt install -y --no-install-recommends pkg-config libglib2.0-dev libcairo2-dev libgirepository1.0-dev python3-dev
  - python -m pip install --user pipx
  - python -m pipx ensurepath
  - pipx install pipenv
  - pipenv install --dev --skip-lock

pytest:
  stage: Test
  allow_failure: false
  script:
    - pipenv run pytest

flake8-vula:
  stage: Test
  allow_failure: true # TODO set to false once code is clean enough
  script:
    - pipenv run flake8 vula/

flake8-test:
  stage: Test
  allow_failure: true # TODO set to false once code is clean enough
  script:
    - pipenv run flake8 test/
