# TODO: We don't have artifacts in woodpecker pipelines (There are plugins like https://woodpecker-ci.org/plugins/S3%20Plugin)
#       so for now we should print out all results to stdout.
# Override default CI env variable for now (see https://github.com/pypa/pipenv/issues/5554)

when:
  event: [push, tag, pull_request, manual]

steps:
  nix:
    depends_on: []
    image: nixos/nix
    environment:
      NIX_CONFIG: extra-experimental-features = nix-command flakes
    commands:
      - system=$(nix-instantiate --eval --expr "builtins.currentSystem")
      - nix build --print-build-logs .#checks.$system.treefmt
      - nix build --print-build-logs

  mypy:
    depends_on: []
    image: python:3.10-bookworm
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - ./misc/install-ci-deps.sh
      - make mypy

  check_test:
    depends_on: []
    image: python:3.10-bookworm
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - ./misc/install-ci-deps.sh
      - . $(pipenv --venv)/bin/activate
      - make check
      - xvfb-run -- pipenv run pytest -v
      - xvfb-run -- pipenv run pytest --cov
      - make sast-analysis
      - make wheel
      - make deb
      - dpkg -I dist/*.deb

  go_test:
    depends_on: []
    image: golang:1.24.4
    commands:
      - apt update && apt install -y clang libclang-rt-19-dev
      - cd contrib/vula-go
      - go install honnef.co/go/tools/cmd/staticcheck@latest
      - go install github.com/securego/gosec/v2/cmd/gosec@latest
      - go install golang.org/x/vuln/cmd/govulncheck@latest
      - go install github.com/kisielk/errcheck@latest
      - go install github.com/gordonklaus/ineffassign@latest
      - go test ./...
      - go test -race ./...
      - CC=clang go test -msan ./...
      - go test -asan ./...
      - staticcheck ./...
      - errcheck ./...
      - govulncheck ./...
      - gosec ./...
