# TODO: We don't have artifacts in woodpecker pipelines (There are plugins like https://woodpecker-ci.org/plugins/S3%20Plugin)
#       so for now we should print out all results to stdout.
# Override default CI env variable for now (see https://github.com/pypa/pipenv/issues/5554)

when:
  event: [push, tag, pull_request, manual]

steps:

  check_test:
    image: python:3.10-bookworm
    commands:
      - export CI=true
      - PATH=$PATH:~/.local/bin
      - ./misc/install-ci-deps.sh
      - . $(pipenv --venv)/bin/activate
      - make check
      - xvfb-run -- pipenv run pytest -v 
      - xvfb-run -- pipenv run pytest --cov
      - make sast-analysis
      - make wheel
      - make deb
      - dpkg -I dist/*.deb
