name: CI

on:
  push:
  pull_request:
  workflow_dispatch:
  create:
    tags: ["*"]

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Nix
        run: |
          curl -L https://nixos.org/nix/install | sh
          . ~/.nix-profile/etc/profile.d/nix.sh
          nix-shell -p nix-info --run "nix-info -m"
      - name: Run Nix builds
        run: |
          system=$(nix-instantiate --eval --expr "builtins.currentSystem")
          nix build --print-build-logs .#checks.${system}.treefmt
          nix build --print-build-logs .

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: |
          export CI=true
          PATH=$PATH:~/.local/bin
          ./misc/install-ci-deps.sh
          make mypy

  check_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Xvfb
        run: |
          sudo apt update
          sudo apt install -y xvfb
      - name: Install CI deps
        run: |
          export CI=true
          PATH=$PATH:~/.local/bin
          ./misc/install-ci-deps.sh
      - name: Run tests
        run: |
          . $(pipenv --venv)/bin/activate
          make check
          xvfb-run -- pipenv run pytest -v
          xvfb-run -- pipenv run pytest --cov
          make sast-analysis
          make wheel
          make deb
          dpkg -I dist/*.deb

  go_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Install Go tools
        run: |
          sudo apt update
          sudo apt install -y clang libclang-rt-19-dev
      - name: Run Go tests
        run: |
          cd contrib/vula-go
          go install honnef.co/go/tools/cmd/staticcheck@latest
          go install github.com/securego/gosec/v2/cmd/gosec@latest
          go install golang.org/x/vuln/cmd/govulncheck@latest
          go install github.com/kisielk/errcheck@latest
          go install github.com/gordonklaus/ineffassign@latest
          go test ./...
          go test -race ./...
          CC=clang go test -msan ./...
          go test -asan ./...
          staticcheck ./...
          errcheck ./...
          govulncheck ./...
          gosec ./...
